---
name: hadolint
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate container images
        run: make test-containers-hadolint
